//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.Scaffolding.WebForms.UI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebFormsScaffolderDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebFormsScaffolderDialogResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.Scaffolding.WebForms.UI.WebFormsScaffolderDialogResources", typeof(WebFormsScaffolderDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string AddButton_Content {
            get {
                return ResourceManager.GetString("AddButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data _context class: 的本地化字符串。
        /// </summary>
        public static string DataContextTypeLabel_Content {
            get {
                return ResourceManager.GetString("DataContextTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master page placeholder ID: 的本地化字符串。
        /// </summary>
        public static string DesktopContentPlaceholderIdLabel_Content {
            get {
                return ResourceManager.GetString("DesktopContentPlaceholderIdLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master page: 的本地化字符串。
        /// </summary>
        public static string DesktopViewsLabel_Content {
            get {
                return ResourceManager.GetString("DesktopViewsLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a master page from the list 的本地化字符串。
        /// </summary>
        public static string Error_DesktopMasterPageRequired {
            get {
                return ResourceManager.GetString("Error_DesktopMasterPageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a model class from the list 的本地化字符串。
        /// </summary>
        public static string Error_ModelTypeRequired {
            get {
                return ResourceManager.GetString("Error_ModelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the ID of the placeholder control to place the generated content in 的本地化字符串。
        /// </summary>
        public static string Error_PlaceholderIdRequired {
            get {
                return ResourceManager.GetString("Error_PlaceholderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model cla_ss: 的本地化字符串。
        /// </summary>
        public static string ModelTypeLabel_Content {
            get {
                return ResourceManager.GetString("ModelTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Over_write existing pages 的本地化字符串。
        /// </summary>
        public static string OverwriteCheckBox_Content {
            get {
                return ResourceManager.GetString("OverwriteCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Web Forms Pages 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Master Page 的本地化字符串。
        /// </summary>
        public static string UseMasterPage {
            get {
                return ResourceManager.GetString("UseMasterPage", resourceCulture);
            }
        }
    }
}
